[package]
name = "service-io"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "sync", "time", "io-std", "io-util"] }
async-trait = "0.1"
whoami = "1.2.1"
